name: "Nightly Build"
on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  pipeline:
    permissions:
      deployments: write
      contents: read
    uses: ./.github/workflows/base.yaml
    with:
      tests: unit, static
    secrets:
      SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
